### PR TITLE
fixes oauth_token being returned as bytes

### PR DESCRIPTION
**Pull request by AnssiAhola**
fixes issue #22

### CODE REVIEW

**Comment by alifhughes** [comment]
Hey @AnssiAhola thanks for finding this and creating a PR to fix it! I've played around with it myself, it does seem to be an issue in fact. I've got no comments on the code itself for this PR, it LGTM. 

However, would you mind trying to add a test around this sort of logic? I realise it is a bit of a hypocritical ask as we (the maintainers) haven't done so either (although we're planning to), but it would prevent possible bugs in this area again and help to make us all more confident of making changes in the future 🙂 Is that okay?

**Comment by AnssiAhola** [comment]
Sure thing @alifhughes, would I make a new file called `test_client.py` and test the `get_access_token` 
or add new test to `test_fetchers.py` that asserts that token is returned from `store_token_from_qs` as `string`?

Which is better in your opinion?

**Review by alifhughes — APPROVED** [review]
LGMT, thanks!

**Comment by alifhughes** [comment]
I've requested a review from other maintainer @JOJ0 just so we both have visibility, once he approves we can merge and I'll look to release it asap for you. Thanks again @AnssiAhola 🙂

**Review by JOJ0 — APPROVED** [review]

**Comment by alifhughes** [comment]
@AnssiAhola this has been released in version 2.3.7 - https://github.com/joalla/discogs_client/releases/tag/v2.3.7

**Pull request merged**
