### PR TITLE
Small fixes for Python 3.12 references #140

### PR DESCRIPTION
**Pull request by arogl**
I did not want to drop earlier python versions.

The dateutil package is awaiting a maintainer release [dateutil#1314](https://github.com/dateutil/dateutil/issues/1314)

### CODE REVIEW

**Comment by JOJ0** [comment]
Hi @arogl 👋 thanks!

I think it's safe to say we should finally ditch 3.6 and 3.7

Please remove and then we'll let the workflows run and see what happens :-)

**Comment by arogl** [comment]
> Hi @arogl 👋 thanks!
> 
> I think it's safe to say we should finally ditch 3.6 and 3.7
> 
> Please remove and then we'll let the workflows run and see what happens :-)

The build could also reference the 3.x from `beets`

```
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.x']
```

**Comment by JOJ0** [comment]
I did some fixes for our docs build, thus merged in master and resolving conflict here.

I'm not sure how we now should fix the issue that `import enum` is not possible for older Python versions (3.8., 3.9.). Any idea @arogl ?

**Comment by arogl** [comment]
> I did some fixes for our docs build, thus merged in master and resolving conflict here.
> 
> I'm not sure how we now should fix the issue that `import enum` is not possible for older Python versions (3.8., 3.9.). Any idea @arogl ?

@JOJ0 I think it will need to be a try/except, or test version >= 3.12.

**Comment by arogl** [comment]
@JOJ0 I am looking at the latest failure and my simple python searching shows I may need to duplicate the function, in an if-else wrapper due to the `@enum.member` decorators not existing in versions of python before 3.12.

Thoughts?

**Comment by JOJ0** [comment]
Oh @AnssiAhola that sounds like a quite clean to read solution. Great idea. Give that a try @arogl 

Let me think about where such a helper def should live...

**Comment by AnssiAhola** [comment]
> Let me think about where such a helper def should live...

Could also just declare the empty decorator in the `except` block? If python allows that.
This way it's not necessary to keep it in some random helper/utils file.

```python
...
except ImportError:
    def member():
        pass
```

**Comment by AnssiAhola** [comment]
Seems like it still fails, because some arguments are being passed to the empty decorator. Hmm...

Maybe try adding *args and **kwargs as parameters.

```python
def member(*args, **kwargs):
    pass
```

**Comment by arogl** [comment]
> Although that might still fail, because we need to return the function that is passed to the decorator 🤔 If that doesn't work try
> 
> ```python
> def member(func):
>     return func
> ```
> 
> Sorry, not on my computer so cant test it myself, hence the trial and error 😅

Second attempt ☹

**Comment by AnssiAhola** [comment]
Wohoo, we have a runner!

**Review by JOJ0 — APPROVED** [review]
It seems the dateutil change mentioned in the initial description is through and release (https://github.com/dateutil/dateutil/pull/1343). I just tested with the latest available version and it seems fine:

```
 pip install python-dateutil==2.9.0.post0
```

```
========================================================================= 50 passed in 0.08s ==========================================================================
 discogs312  ~/git/discogs_client   arogl-patch-1 
 discogs312  ~/git/discogs_client   arogl-patch-1  python-dateutil
 ✘  discogs312  ~/git/discogs_client   arogl-patch-1  python -m unittest discover
..................................................
----------------------------------------------------------------------
Ran 50 tests in 0.006s

OK
 discogs312  ~/git/discogs_client   arogl-patch-1  pytest
========================================================================= test session starts =========================================================================
platform darwin -- Python 3.12.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/jtiefenbacher/git/discogs_client
collected 50 items

discogs_client/tests/test_core.py ............                                                                                                                  [ 24%]
discogs_client/tests/test_fetchers.py ..                                                                                                                        [ 28%]
discogs_client/tests/test_models.py .............................                                                                                               [ 86%]
discogs_client/tests/test_utils.py .......                                                                                                                      [100%]

========================================================================= 50 passed in 0.08s ==========================================================================
 discogs312  ~/git/discogs_client   arogl-patch-1 
 ```

Thanks @arogl and @AnssiAhola for your great team effort! :-*

**Comment by JOJ0** [comment]
I'm just not sure what i could do about the kind of "hanging" build (3.6/3.7) CI checks. To trigger a re-run I'll now close and reopen the PR.

**Comment by JOJ0** [comment]
Ok I assume this is a bug. It should go away in future CI runs since we kicked out 3.6 and 3.7 build with this one.

**Comment by JOJ0** [comment]
> Ok I assume this is a bug. It should go away in future CI runs since we kicked out 3.6 and 3.7 build with this one.

Yep, all green in master now  :-)

**Pull request merged**
