### PR TITLE
Update Docs: Add remove_release docs 

### PR DESCRIPTION
**Pull request by prcutler**
Here are potential docs for the new remove_release.  I made two changes, renaming the page to 'Managing Release and Collection data' and then added the code example from PR #88 as documentation.

Let me know if you want any changes made, I'm open to feedback.

Paul

### CODE REVIEW

**Comment by JOJ0** [comment]
Hi, thanks a lot for the submission. Great! Anssi already added some to the docs within his PR: https://github.com/joalla/discogs_client/pull/88/commits/fe551834bf98321c29dffeda6befaae66a678696. Let's wait for it to go through and I think we could add your usage example as well to the chapter.

**Comment by AnssiAhola** [comment]
Hey @prcutler 
I merged PR #88 into master and it had some changes to the docs.
Theres probably some conflicts.

Feel free to make any addition/changes/clarification to the docs I added!

**Review by JOJ0 — APPROVED** [review]

**Comment by JOJ0** [comment]
Hi @AnssiAhola and @prcutler, apologies for quickly merging both of your ideas, I want to kick out a release today and not want to wait too long. I hope you're fine with my merge, I could still change stuff in master if you have a quick suggestion: https://python3-discogs-client.readthedocs.io/en/latest/fetching_data.html#adding-a-release-to-a-collection-folder

**Comment by AnssiAhola** [comment]
LGTM! I like it. Thank you!

**Pull request merged**
