### PR TITLE
Add Community Details docs chapter

### PR DESCRIPTION
**Pull request by JOJ0**
Some examples and point to the Sphinx reference docs for the rest.

### CODE REVIEW

**Review by prcutler — COMMENTED** [review]
In fetching_data.md, what do you think about:

Additional attributes are also available.  Learn more about them in the reference docs of the {class}`~discogs_client.models.CommunityDetails` class.

Thanks for doing this!

**Comment by JOJ0** [comment]
This is how the rendered reference docs now look like for these two classes. The longish inherited docstrings "An attribute that determines its value using the object’s fetch() method....." coming from the descriptors in use is now gone thanks to the `#: ` comments.

@AnssiAhola what do you think about my short descriptions of the classes in the docstrings. Technically correct? Or should I rather refer to the JSON object "community" or the "/releases/id endpoint" instead of simply Release object.

Screenshot 2022-08-22 at 08 32 13

**Comment by AnssiAhola** [comment]
Something like
> An object that wraps the "community" data found in a `Release`.
> See https://www.discogs.com/developers#page:database,header:database-release-get

Or is the external link necessary?
`Release` would be a link to the models docs

**Comment by JOJ0** [comment]
I think I'll go with just the link to the Release class. I'll note here that the syntax is slightly different than we've used before directly in .md files. Use colons instead of curly brackets. Eg: `:class:`classname`` or `:method`.methodname``

**Review by AnssiAhola — APPROVED** [review]
LGTM! 👍

**Pull request merged**
