### PR TITLE
Added `date_added` to CollectionItem. Fixed `parse_timestamp`

### PR DESCRIPTION
**Pull request by alifhughes**
- Support request was raised [here](https://github.com/joalla/discogs_client/discussions/32) for adding `date_added` to a `CollectionItemInstance` which is available in the response [here](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release)
- When testing `parse_datetime` I noticed that it was throwing the error:
```python
>>> me.registered                                                                                                                                             
Traceback (most recent call last):                                                                                                                            
  File "<stdin>", line 1, in <module>                                                                                                                         
  File "/Users/alistair.hughes/Documents/joalla/discogs_client/discogs_client/models.py", line 28, in __get__                                                 
    value = self.transform(value)                                                                                                                             
  File "/Users/alistair.hughes/Documents/joalla/discogs_client/discogs_client/utils.py", line 7, in parse_timestamp                                           
    return datetime.strptime(timestamp, '%Y-%m-%dT%H:%M:%S')                                                                                                  
  File "/Users/alistair.hughes/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime                                             
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)                                                                                            
  File "/Users/alistair.hughes/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 362, in _strptime                                                      
    data_string[found.end():])                                                                                                                                
ValueError: unconverted data remains: -07:00 
```
- After looking at the API response ([here](https://www.discogs.com/developers/#page:user-collection,header:user-collection-collection-items-by-release)), I see that they've included `timezone` in the datetime, which i've added to the `parse_timestamp` function [here](https://github.com/joalla/discogs_client/compare/master...alifhughes:date-added-to-collection-item?expand=1#diff-bf0a04086fea90a5377ed0df81ee065411fb02843a24d900d76096406bcdd043R7)
    - **As far as I could test, this is broken in master currently too**, example being:
```python
>>> import discogs_client
>>> d = discogs_client.Client('ExampleApplication/0.1', user_token="....")
>>> me = d.identity()
>>> me.registered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alistair.hughes/Library/Caches/pypoetry/virtualenvs/test-client-wzn_dOLX-py3.7/lib/python3.7/site-packages/discogs_client/models.py", line 28, in __get__
    value = self.transform(value)
  File "/Users/alistair.hughes/Library/Caches/pypoetry/virtualenvs/test-client-wzn_dOLX-py3.7/lib/python3.7/site-packages/discogs_client/utils.py", line 7, in parse_timestamp
    return datetime.strptime(timestamp, '%Y-%m-%dT%H:%M:%S')
  File "/Users/alistair.hughes/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/Users/alistair.hughes/.pyenv/versions/3.7.7/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: -07:00
>>> 
```

### CODE REVIEW

**Comment by alifhughes** [comment]
Looking into the `python 3.6.12` test failures 👀

**Comment by alifhughes** [comment]
it seems that `python 3.6` cannot parse date times with a colon in it. My commit is a solution to this based off of this answer [here](https://stackoverflow.com/questions/30999230/how-to-parse-timezone-with-colon). My preferred solution would be to deprecate python 3.6 rather than creating custom code to support it. But perhaps I think that is out of scope for this PR.

**Comment by hellricer** [comment]
Personally, I'd vouch the 3rd party lib solution rather than the string manipulation.

3.6 is still supported until December, so I'd wait with deprecation until then.

**Comment by alifhughes** [comment]
> Personally, I'd vouch the 3rd party lib solution rather than the string manipulation.
> 
> 3.6 is still supported until December, so I'd wait with deprecation until then.

I'd go for the 3rd party package too, @JOJ0 all good with you?

**Comment by JOJ0** [comment]
sure, dateutil is a very handy package and I suppose well maintained too.

**Comment by alifhughes** [comment]
@hellricer @JOJ0 think this is ready for review again when you have a moment 🙂 I'd appreciate if you could give it a installation test, I've installed it and seems to pull in the `dateutil` library fine and work - just extra set of eyes wouldn't go a miss!

**Comment by VinylVault** [comment]
how can i test this to help it get through approval?

**Comment by JOJ0** [comment]
I’ll take a look tomorrow morning.

**Comment by JOJ0** [comment]
> how can i test this to help it get through approval?

directly install the discogs client package from alifhughes branch. I’ll send a pip install command tomorrow.

**Comment by JOJ0** [comment]
> @hellricer @JOJ0 think this is ready for review again when you have a moment 🙂 I'd appreciate if you could give it a installation test, I've installed it and seems to pull in the `dateutil` library fine and work - just extra set of eyes wouldn't go a miss!

Just did a `python setup.py install`, but with python3.7 only. It runs fine and played around with your test as well. It took me ages to get what you did with timezone but probably I am just too bad of a programmer to work with times haha ;-)

Anyway, does it hurt if you put some simpler examples too? :-)))
```
self.assertEqual(
            p('1930-07-27T08:11:29-00:00'),
            datetime(1930, 7, 27, 8, 11, 29, tzinfo=timezone.utc)
        )
        self.assertEqual(
            p('2055-07-27T08:11:29-07:00'),
            datetime(2055, 7, 27, 8, 11, 29, tzinfo=timezone(timedelta(hours=-7)))
        )
```

**Comment by JOJ0** [comment]
> > how can i test this to help it get through approval?
> 
> directly install the discogs client package from alifhughes branch. I’ll send a pip install command tomorrow.

If you want to test this version of python3-discogs-client package in your own program, just install directly from git into your dev venv:

`pip install -e git+https://github.com/alifhughes/discogs_client@backoff-on-ratelimit#egg=python3-discogs-client`

alternatively, if your program has it's own `requirements.txt`, put this line instead of the `python3-discogs-client>=x.x.x` line:

`-e git+https://github.com/alifhughes/discogs_client@backoff-on-ratelimit#egg=python3-discogs-client`

and reinstall all requirements with: `pip install -r requirements.txt`

**Comment by VinylVault** [comment]
@JOJ0 similar issues with this command
```console
pip3 install -e git+https://github.com/alifhughes/discogs_client@date-added-to-collection#egg=python3-discogs-client
Obtaining python3-discogs-client from git+https://github.com/alifhughes/discogs_client@date-added-to-collection#egg=python3-discogs-client
  Updating ./src/python3-discogs-client clone (to revision date-added-to-collection)
  Did not find branch or tag 'date-added-to-collection', assuming revision or ref.
fatal: ambiguous argument 'date-added-to-collection': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command "git reset --hard -q date-added-to-collection" failed with error code 128 in /home/dex/pythoncode/Vault2022/src/python3-discogs-client
```

**Comment by JOJ0** [comment]
sorry -item missing in branch name

**Comment by alifhughes** [comment]
> Anyway, does it hurt if you put some simpler examples too? :-)))

@JOJ0 Good idea, done it 👍 Ready for review/merge 🙂

**Review by JOJ0 — APPROVED** [review]

**Pull request merged**
