### PR TITLE
Add community details to Release

### LINKED ISSUE #104: Add community related details to Release
### Discussed in https://github.com/joalla/discogs_client/discussions/101

> <div type='discussions-op-text'>
> 
> <sup>Originally posted by **amoe** June  9, 2022</sup>
> Hi, great work on the client.
> 
> How could I retrieve the average rating?
> 
> For instance, this page shows the rating: https://www.discogs.com/master/1837544-Netsky-Second-Nature
> Which is 4.6 as of this writing.
> 
> I'm also interested in how to fetch the number of users who have a master or release in their collection, does the API make this data available?</div>

Following data is present in [GET Release API](https://www.discogs.com/developers#page:database,header:database-release-get) point

```json
"community": {
    "contributors": [
        {
            "resource_url": "https://api.discogs.com/users/memory",
            "username": "memory"
        },
        {
            "resource_url": "https://api.discogs.com/users/_80_",
            "username": "_80_"
        }
    ],
    "data_quality": "Correct",
    "have": 252,
    "rating": {
        "average": 3.42,
        "count": 45
    },
    "status": "Accepted",
    "submitter": {
        "resource_url": "https://api.discogs.com/users/memory",
        "username": "memory"
    },
    "want": 42
}
```
I think at least `have`, `want` and `rating` fields should be available through properties in `Release` object
Example.
```python
>>> print(release.want)
>>> 42
>>> print(release.have)
>>> 252
>>> print(release.rating)
>>> <Rating avg 3.42>
```

Couldn't find a way to get this information for Master releases so this would be for releases only

### PR DESCRIPTION
**Pull request by AnssiAhola**
Adds community related fields from [GET Release API](https://www.discogs.com/developers#page:database,header:database-release-get)

closes #104

Usage
```python
release = client.release(15343679)
community_details = release.community

print(community_details)
>>> <CommunityDetails want/have: 34/74>
print (community_details.rating)
>>> <Rating avg: 4.5>
print(community_details.want)
>>> 34
print(community_details.have)
>>> 74
print(community_details.status)
>>> Accepted
print(community_details.data_quality)
>>> Needs Vote
print(community_details.contributors)
>>> [<User 1053297 'ManikRecs'>, <User 1241908 'neurosis76'>, <User 8867757 'silyn1'>, <User 3410038 'evasstra'>]
print(community_details.submitter)
>>> <User 1053297 'ManikRecs'>
```

### CODE REVIEW

**Comment by AnssiAhola** [comment]
@JOJ0 Let me know if there's something I should fix/change before merging this.
Long overdue :sweat_smile:

**Comment by JOJ0** [comment]
Thanks for getting this rolling again Anssi! I think your idea of summarising under a community object is good. It took me a while though to find out which api endpoints are actually used for this object. We should document this object and where its data is fetched from to have answers for the kind of question: Are you supporting discogs api endpoint X?

I dont have time for testing atm but think this is save to merge.

If you feel like quickly putting your example above plus api endpoints to a docs chapter, work away. Paul or me might polish it later on :-) Just so we have the necessities in.

**Review by JOJ0 — APPROVED** [review]

**Comment by AnssiAhola** [comment]
Something like this?
**supported_api_points.md**
> Here are the API points currently supported by the client
> - [Release](https://www.discogs.com/developers#page:database,header:database-release)
> - [Artist](https://www.discogs.com/developers#page:database,header:database-artist-get)
> - [Listing](https://www.discogs.com/developers#page:marketplace,header:marketplace-listing-get)
> - [Listing - Edit](https://www.discogs.com/developers#page:marketplace,header:marketplace-listing-post)
> - ...

Basically showing same things that are in the [official docs](https://www.discogs.com/developers) (that we support anyways)

**Comment by JOJ0** [comment]
No, I think you misunderstood or I didn't explain well what I ment. I was talking about adding a docs chapter about this feature and then put the relation that what API's this feature is using to make that clear.

Your approach of having a general list of "that's what we support" is definitely good for the library user to have it in one place but I am not sure if I want to go down that road. I did that for another project and for that one it's manageable but I am sure it's outdated again already (https://github.com/JOJ0/synadm#implementation-status--commands-list). We would have to be behind it or rely on others to keep it updated with every PR. We can think about it yes, but I'm not sure yet...

**Comment by JOJ0** [comment]
But hey Anssi, maybe _I_ did misunderstand: Is all this actually fetched from the release endpoint only? 

This tells me it is: https://github.com/joalla/discogs_client/discussions/101#discussioncomment-2916599

**Comment by JOJ0** [comment]
Yesterday when fiddling around on my mobile and try to read throught api docs and your code I thought this feature uses several of these "sub-endpoints" to fetch things: https://www.discogs.com/developers#page:database,header:database-community-release-rating

But that's not the case I think.

Is that just an alternative way of fetching ev. have's and want' I'm wondering? And by default it's contained in the plain release endpoints result already?

**Comment by AnssiAhola** [comment]
Yes this data is actually part of the Release API response JSON
https://www.discogs.com/developers#page:database,header:database-release-get

and actually has more info than the community release rating endpoint you linked

I'm not sure if this info was added recently to the endpoint or why wasn't it added to the `Release` object already :shrug:

**Comment by JOJ0** [comment]
Let's merge it. Even played around a little with. I think it's great!

**Pull request merged**
