### PR TITLE
Add attribute artists_sort to Release class

### PR DESCRIPTION
**Pull request by JOJ0**
To support a feature request in beetbox/beets: https://github.com/beetbox/beets/issues/4401#top, laying out this information via the client might help.

### CODE REVIEW

**Review by AnssiAhola — APPROVED** [review]
LGTM!

Is this basically alternative to artist.fetch("join")?
That's also one field we could add to the Artist model at some point :sweat_smile:

**Comment by JOJ0** [comment]
No actually it's a way to get the joined artists in a string directly from the api. have a look into the linked beets issue for an example.

**Comment by JOJ0** [comment]
I misread your message @AnssiAhola, yes it definitely _is_ an alternative to manually joining artist! Sorry! Yeah! :sweat_smile:

**Comment by JOJ0** [comment]
Unfortunately even though docs rendering went fine on my machine, it seams we hit an issue again: https://readthedocs.org/projects/python3-discogs-client/builds/18164644/

Will look into another time...

**Comment by JOJ0** [comment]
Fixed it, was an issue in latest Sphinx version. Pinnend it to older one as documented here: https://github.com/readthedocs/sphinx_rtd_theme/issues/1343

@prcutler @AnssiAhola @alifhughes have a look into diff of this PR, this is how we can document class attributes and this is how it looks like rendered:
https://python3-discogs-client.readthedocs.io/en/latest/discogs_client.html#discogs_client.models.Release.artists

**Pull request merged**
