### PR TITLE
Enums for condition, status and sort(by/order)

### PR DESCRIPTION
**Pull request by AnssiAhola**
also adds more imports to __init__.py

I tried to collect all strings I could find in the docs, there was three special conditions that the media condition does not accept but the sleeve condition does, `Generic`, `Not Graded` and `No Cover`

### CODE REVIEW

**Comment by JOJ0** [comment]
Hey Anssi, thanks for another great contribution to the project! I will take a closer a look this weekend. Sorry for letting you wait!

Some thoughts on the first looks: Easy and I think can't break much and is a good idea. Some usage examples would help me though or even better, when you are at it already: Why don't you add some examples on how these condition and sorting enums can be used to the readme?

**Comment by alifhughes** [comment]
Hey @AnssiAhola, similar to @JOJ0, sorry for making you wait! Thanks again for the contribution. All looks good to me, like @JOJ0 said would be nice to maybe include a small bit in the `README.md` just make users aware of it who don't look in the code. Also just a thought, wasn't 100% sure whether `utils.py` is the best place for them? Could be under `models.py` 🤔 Not sure really, no strong preference, see if @JOJ0 or @hellricer think any different, if not happy to leave as is.

**Comment by JOJ0** [comment]
because of docs: maybe the whole condition thing should be demonstrated in a chapter in readme describing how to add sales listings and use these enums

but then it us subject to another pr

not sure about where to document the sorting things though...

**Comment by JOJ0** [comment]
move to models sounds right but not sure either. @hellricer  will decide haha

**Comment by JOJ0** [comment]
one more thing: why we need imports in init at all? probably i am missing something but bold enough to ask 😬

**Comment by AnssiAhola** [comment]
> 
> 
> Also just a thought, wasn't 100% sure whether `utils.py` is the best place for them? Could be under `models.py` 🤔 

> 
> 
> move to models sounds right but not sure either. hellricer will decide haha

😄 My thinking was that these are QOL additions/utilities and not really core models/features.

> 
> 
> one more thing: why we need imports in init at all? probably i am missing something but bold enough to ask 😬

I was thinking the same thing, haha, but figured if some are allready imported, why not the rest? 🤔


I'll add some documentation to README about just the enums.

**Comment by JOJ0** [comment]
> > Also just a thought, wasn't 100% sure whether `utils.py` is the best place for them? Could be under `models.py` 🤔
> 
> > move to models sounds right but not sure either. hellricer will decide haha
> 
> 😄 My thinking was that these are QOL additions/utilities and not really core models/features.

Alright for me, let's leave them here :-)

> > one more thing: why we need imports in init at all? probably i am missing something but bold enough to ask 😬

> I was thinking the same thing, haha, but figured if some are allready imported, why not the rest? 🤔

Ok, right, at least it's a more complete list of imports now. I'll discuss with the others if they make sense for some reason or we remove them in another PR.

> I'll add some documentation to README about just the enums.
> Or should I make a new PR where I document the adding and editing of listing too?

If you have the time for a PR like this, that would be really awesome! Our docs are, well... pretty bad I have to admit haha :-)

**Review by JOJ0 — COMMENTED** [review]
I think this is fine and can be merged. Agreed @alifhughes and @hellricer ?

**Review by alifhughes — APPROVED** [review]
LGTM, I would like a documentation update, but I think it can be done in a separate PR and include the listing adding/editing you did in the last PR. It doesn't have to be verbose, just small example like what is currently there would be amazing 🙂 Great work again, thank you @AnssiAhola! P.S thanks for the review as well @JOJ0 👍

**Pull request merged**
