### PR TITLE
Add join attribute to Artist class and

### PR DESCRIPTION
**Pull request by JOJ0**
document it via autodoc autoattribute (#:).

Also fixes/unclutters all the other (child)classes in models.py by adding empty autoattribute comments.

### CODE REVIEW

**Comment by JOJ0** [comment]
Besides adding a new field to Artist objects, this PR should fix our cluttered Sphinx doc of models.py once and for all.

@prcutler suggestions for improving my wording of the new "join" attribute are very welcome :-)

@anssiahola In case you know by heart: See the FIXME in my commit. Could an Artist in the artists list of a Track object also contain the "join" information?

One issues with documenting via autoattribute (#: comments) I can't figure out or mabe it's even just not possible: How to put links to other objects within these comments. Eg. here (from my previous PR) I tried to mark that I'm talking about another object but it's not a link, just text: https://python3-discogs-client.readthedocs.io/en/latest/discogs_client.html#discogs_client.models.Release.artists

**Review by prcutler — CHANGES_REQUESTED** [review]
I think using join is fine - you could use combine, too.  I would remove the quotes from join as its the right word.

I'm trying to re-write the second sentence.  What does this refer to?  The first result?
```
first of the artists does contain
    #: a keyword like 
```

**Comment by AnssiAhola** [comment]
> In case you know by heart: See the FIXME in my commit. Could an Artist in the artists list of a Track object also contain the "join" information?

Tried to look into this a bit and I don't think the `artists` field is ever populated. Only the `credits`/`extraartists` field is and that does seem to contain artists with the `join` field as well

**Comment by JOJ0** [comment]
> 
> I'm trying to re-write the second sentence.  What does this refer to?  The first result?
> 
> ```
> 
> first of the artists does contain
> 
>     #: a keyword like 
> 
> ```
> 
> 
> 
only the first Artist object in the artist list does contain the join keyword. have a look in the linked beets issue in one of my posts youll find an example json snippet

**Comment by JOJ0** [comment]
> > In case you know by heart: See the FIXME in my commit. Could an Artist in the artists list of a Track object also contain the "join" information?
> 
> Tried to look into this a bit and I don't think the `artists` field is ever populated. Only the `credits`/`extraartists` field is and that does seem to contain artists with the `join` field as well

Thanks for digging in Anssi!

I took the example from the beets issue again and had a look in the original api response, looks like that (really just 1 track on that record):

```
 "tracklist": [
    {"position": "1", "type_": "track", "title": "Bassface", "duration": "5:12"}
],
"extraartists": [
    {"name": "MC Freestyle", "anv": "", "join": "", "role": "Featuring", "tracks": "", "id": 336113, "resource_url": "https://api.discogs.com/artists/336113"}
],
 ```

But I guess that's something to think about in another PR I'd say, now I'll concentrateon the Artist object

**Comment by JOJ0** [comment]
@prcutler what you think about this slightly changed version:

```
    #: This attribute is only populated when an ``Artist`` object is requested
    #: via the ``artists`` list of an ``Release`` object, and if it is a
    #: multi-artist release. Usually only the first ``Artist`` object in the artists list does contain
    #: a keyword like  "And", "Feat", "Vs", or similar. This keyword could be used to combine artists
    #: together into a single string like eg. "DJ ABC Feat MC Z". Also check out the artists_sort attribute
    #: of a ``Release`` object.
```

**Comment by JOJ0** [comment]
@prcutler fixed as suggested. Thanks a lot! :-) Please accept the change, I'll merge then. Thanks!

**Review by prcutler — APPROVED** [review]

**Comment by prcutler** [comment]
Done!  Looks good and thanks!

**Pull request merged**
